### ISSUE TITLE
sh scripts/utils/launch_MyBigGAN.sh error, FileNotFoundError: [Errno 2] No such file or directory: 'pos.npy'.

### ISSUE THREAD

**Issue by Ashchenlovelive** [bxz9200/CLPA#1]
Run sh scripts/utils/launch_MyBigGAN.sh as indicated.
Got error,
```
Traceback (most recent call last):
  File "train.py", line 29, in <module>
    import train_fns
  File "/home/CLPA/train_fns.py", line 19, in <module>
    pos = np.load("pos.npy")
  File "/home/anaconda3/envs/CLPA/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'pos.npy'
```
It looks like the error is due to the lack of "pos.npy". May I ask how to generate 'pos.noy'? Thanks a lot.

**Comment by bxz9200** [comment]
Hi, thank you for the attention to our work and thank you for the question.

pos.npy contains the positive centroid (i.e., mean features of images that are correctly classified) of each class. neg.npy contains the negative centroid (i.e., mean features of images that are misclassified) of each class. We present the detailed procedures in our paper (Algorithm 2), where you can refer to for details.

**Comment by bxz9200** [comment]
> Run sh scripts/utils/launch_MyBigGAN.sh as indicated. Got error,
> 
> ```
> Traceback (most recent call last):
>   File "train.py", line 29, in <module>
>     import train_fns
>   File "/home/CLPA/train_fns.py", line 19, in <module>
>     pos = np.load("pos.npy")
>   File "/home/anaconda3/envs/CLPA/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
>     fid = stack.enter_context(open(os_fspath(file), "rb"))
> FileNotFoundError: [Errno 2] No such file or directory: 'pos.npy'
> ```
> 
> It looks like the error is due to the lack of "pos.npy". May I ask how to generate 'pos.noy'? Thanks a lot.

Hi, thank you for the attention to our work and thank you for the question.

pos.npy contains the positive centroid (i.e., mean features of images that are correctly classified) of each class. neg.npy contains the negative centroid (i.e., mean features of images that are misclassified) of each class. We present the detailed procedures in our paper (Algorithm 2), where you can refer to for details.

**Comment by Ashchenlovelive** [comment]
Thank you very much for your reply. Could you please upload 'pos.npy' and 'neg.npy'?

**Comment by nil0330** [comment]
I have the same issue and would like to run the code from the paper. Would it be possible to upload 'pos.npy' and 'neg.npy' files?

**Comment by bxz9200** [comment]
> Thank you very much for your reply. Could you please upload 'pos.npy' and 'neg.npy'?

Please refer to these to files in the scripts folder. Thank you.

**Comment by bxz9200** [comment]
> I have the same issue and would like to run the code from the paper. Would it be possible to upload 'pos.npy' and 'neg.npy' files?

Hi, I just uploaded these two files. Please find them in the scripts folder. Thank you.
